name: Deploy via ftp

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - uses: actions/checkout@v2
        - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: ${{ secrets.FTP_USERNAME }}
              server: ${{ secrets.FTP_SERVER }}
              password: ${{ secrets.FTP_PASSWORD }}
              local_path: '/dist'
              remote_path: '/var/www/dawnps.com/public_html'
              sftpArgs: '-o ConnectTimeout=5'
